import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { app, database } from "../../utils/firebase";
import { collection, getDocs } from "firebase/firestore";
import { useCollectionData } from "react-firebase-hooks/firestore";
import Navbar from "../components/navbar/Navbar";

export default function Home() {
  const [users, setUsers] = useState([]);
  const dbInstance = collection(database, "users");
  const [docs, loading, error] = useCollectionData(dbInstance);

  console.log("docs", docs);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <h1 className="bg-blue-300">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="bg-blue-500">
          {docs?.map((user, index) => {
            return (
              <div key={index + 1} className="text-lg">
                <p>{user.username}</p>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
